//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requests()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int requestID { get; set; }
        public string computerTechType { get; set; }
        public string computerTechModel { get; set; }
        public string problemDescryption { get; set; }
        public string requestStatus { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterID { get; set; }
        public int clientID { get; set; }
    
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual masters masters { get; set; }
    }
}
