//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRequests
    {
        public int requestID { get; set; }
        public int userID { get; set; }
        public string fio { get; set; }
        public string phone { get; set; }
        public string computerTechType { get; set; }
        public string computerTechModel { get; set; }
        public string problemDescryption { get; set; }
    
        public virtual users users { get; set; }
    }
}
